/** @format */

import { Metadata } from "next";
import React from "react";

type Props = {};

export const metadata: Metadata = {
  title: "ini login",
  description: "Generated by create next app",
};
export default function page({}: Props) {
  return <div>login</div>;
}
