/** @format */

import { Metadata } from "next";
import React from "react";

type Props = {};
export const metadata: Metadata = {
  title: "Not Found Page",
  description: "Generated by create next app",
};

export default function NotFound({}: Props) {
  return <div>Not Found Page</div>;
}
