/** @format */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import ContextProvider from "@/providers/context.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <Navbar />
          <div className="flex justify-center w-full">
            <div className=" mt-16 mx-5  w-full max-w-screen-xl">
              {children}
            </div>
          </div>
        </ContextProvider>
      </body>
    </html>
  );
}
