/** @format */

import type { Metadata } from "next";
import "./globals.css";
import NavbarDesktop from "@/components/navbar/navbar.desktop";
import Footer from "@/components/footer/footer";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
export const metadata: Metadata = {
  title: "KFC Chicken Indonesia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <NavbarDesktop />
          {children}
          <Footer />
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
